version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=192.168.188.45
  octane:
    build: ./laravel-octane
    expose:
    - 9000
    environment:
      - VIRTUAL_HOST=octane.localhost
      - VIRTUAL_PORT=9000
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  nextjs:
    build: ./nextjs/nextjs-docker
    expose:
    - 3000
    environment:
    - VIRTUAL_HOST=192.168.188.45
    - VIRTUAL_PORT=3000
volumes:
  database: